println("horas de trabajo")
val hrstrab = read float ()
for  (i <= 40 && i >40)
if (i <= 40 )
printl ("salario por hora es $160")
else if (i > 40)
println ("salario por hora es $160 + 200 hora extra")
println ("horas de trabajo")
val Horas de trabajo = read float()
printl("salario por semana es ")
for (i<=40 )
 println (salario = horas * 160)
printl("salario por semana ")
for (i > 40 )
 println (salario = horas * 160 && i + 200 )
