println ("monto")
val monto = read float()
if (i >= 500000)
println (monto - 55% - 30%)
println ("cantidad que debe pagar ")
println ("empresa =" monto-55%")
println ("banco =" monto- 30%)
println ("credito fabricante =" monto-15%)
else (i < 500000)
println (monto -70% - 30%)
println ("cantidad que debe pagar " )
println ("empresa =" monto-70%")
println ("credito fabricante =" monto-30%)
println ("total a fabricante = " credito fabricante - 20%)
